var nameList = [
  "James",
  "Emily Johnson",
  "Michael",
  "Jessica",
  "Robert",
  "Sarah Wilson",
  "William",
  "Grace Thompson",
  "Daniel",
  "Olivia White",
  "Joseph Moore",
  "Ava",
  "Benjamin Walker",
  "Avery Young",
  "Harper Phillips",
  "Mason Thompson",
  "Evelyn Allen",
  "Ethan",
  "Isabella Clark",
  "Alexander Davis",
  "Mia",
  "Ethan Davis",
  "Avery Johnson",
  "Mason Davis",
  "James Wilson",
  "Benjamin Brown",
  "Olivia Taylor",
  "Daniel Thompson",
  "Grace Clark",
  "William Anderson",
  "Sarah",
  "Joseph Lewis",
  "Emily Phillips",
  "Alex",
  "Ava",
  "Ben",
  "Bella",
  "Charlie",
  "Chloe",
  "Dan",
  "Emma",
  "Ethan",
  "Ella",
  "Finn",
  "Grace",
  "Hannah",
  "Jack",
  "Jessica",
  "James",
  "Katie",
  "Liam",
  "Lily",
  "Mason",
  "Mia",
  "Noah",
  "Olivia",
  "Oliver",
  "Sophia",
  "William",
  "Zoe",
  "Zach",
  "Avery",
  "Bryson",
  "Caleb",
  "Dakota",
  "Eli",
  "Eva",
  "Fiona",
  "Gabriel",
  "Harper",
  "Ivy",
  "Jaxon",
  "Julia",
  "Kai",
  "Leah",
  "Logan",
  "Madison",
  "Nathan",
  "Parker",
  "Quinn",
  "Riley",
  "Skylar",
  "Theo",
  "Violet",
  "Wyatt",
  "Xavier",
  "Yara",
  "Zara",
  "Sarah Miller",
  "Joseph Johnson",
  "Emily Davis",
  "Robert Taylor",
  "Isabella Anderson",
  "Alexander White",
  "Harper Thompson",
  "Mia Brown",
  "Ethan Davis",
  "Avery Johnson",
  "James Clark",
  "Benjamin Wilson",
  "Olivia Davis",
  "Daniel Brown",
  "Grace Miller",
  "William Johnson",
  "Sarah Taylor",
  "Joseph Thompson",
  "Emily Clark",
  "Robert Lewis",
  "Isabella Young",
  "Aaliyah",
  "Aiden",
  "Avery",
  "Bella",
  "Benjamin",
  "Charlotte",
  "Daniel",
  "Ella",
  "Eli",
  "Fiona",
  "Gabriel",
  "Hailey",
  "Isabella",
  "Jackson",
  "Jasmine",
  "Jaxon",
  "Kaitlyn",
  "Liam",
  "Madison",
  "Nathan",
  "Olivia",
  "Oliver",
  "Penelope",
  "Quinn",
  "Riley",
  "Sophia",
  "Theodore",
  "Violet",
  "William",
  "Xavier",
  "Zoey",
  "Aaron",
  "Adam",
  "Brianna",
  "Carter",
  "Diana",
  "Evan",
  "Faith",
  "Gavin",
  "Heidi",
  "Ivan",
  "Jayden",
  "Kenneth",
  "Lila",
  "Mateo",
  "Nora",
  "Owen",
  "Paisley",
  "Quentin",
  "Ruby",
  "Samuel",
  "Tessa",
  "Uriel",
  "Victor",
  "Wyatt",
  "Yara",
  "Zander",
  "Olivia Wilson",
  "Daniel Thompson",
  "Grace Lewis",
  "William Young",
  "Sarah Miller",
  "Joseph Johnson",
  "Emily Davis",
  "Robert Taylor",
  "Isabella Anderson",
  "Alexander White",
  "Harper Thompson",
  "Mia Brown",
  "Ethan Davis",
];

var messagesList = [
  "OMG, I love this video!",
  "This is so cool!",
  "Wow, I can't believe it!",
  "This is amazing!",
  "I'm learning so much!",
  "😀",
  "😂",
  "🤣",
  "😃",
  "😄",
  "This is so helpful!",
  "Thanks for sharing!",
  "This is so inspiring!",
  "I'm so glad I found this!",
  "This is so interesting!",
  "I'm hooked!",
  "This is so fun!",
  "I'm loving this!",
  "😅",
  "😆",
  "😉",
  "😊",
  "😋",
  "This is so awesome!",
  "I'm so excited!",
  "This is so cool!",
  "I'm so impressed!",
  "This is so informative!",
  "I'm so grateful!",
  "This is so entertaining!",
  "I'm so happy!",
  "This is so relatable!",
  "I'm so motivated!",
  "😎",
  "😍",
  "😘",
  "😗",
  "😙",
  "😚",
  "This is so funny!",
  "I'm so inspired!",
  "This is so clever!",
  "I'm so amazed!",
  "This is so impressive!",
  "I'm so thrilled!",
  "This is so enlightening!",
  "I'm so thankful!",
  "This is so captivating!",
  "I'm so engaged!",
  "This is so enjoyable!",
  "I'm so glad I watched this!",
  "This is so enriching!",
  "I'm so glad I found this channel!",
  "😇",
  "😈",
  "👿",
  "😛",
  "😜",
  "😝",
  "🤓",
  "😎",
  "This is so valuable!",
  "I'm so excited to learn more!",
  "This is so well done!",
  "I'm so impressed with your skills!",
  "This is so insightful!",
  "I'm so grateful for your advice!",
  "This is so refreshing!",
  "I'm so glad I stumbled upon this!",
  "This is so empowering!",
  "I'm so excited to try this!",
  "This is so informative and helpful!",
  "This is so inspiring and motivational!",
  "I'm so glad I decided to watch this!",
  "Hey, what's up?",
  "Hi there!",
  "Hey!",
  "Hi!",
  "Heya!",
  "Yo!",
  "Heyo!",
  "Hiya!",
  "How's it going?",
  "What's good?",
  "What's up?",
  "What's new?",
  "Long time no see!",
  "Nice to meet you.",
  "Thanks for joining the chat.",
  "Hope you're having a good day.",
  "What brings you here today?",
  "How did you find this channel?",
  "What do you think of this video?",
  "😞",
  "😔",
  "😟",
  "😠",
  "😡",
  "🤬",
  "Have you tried this before?",
  "What's your favorite part so far?",
  "Do you have any questions?",
  "I'm here to help if you need anything.",
  "Let me know if you have any feedback.",
  "Glad to see you're enjoying the video.",
  "Thanks for watching!",
  "Don't forget to like and subscribe.",
  "See you in the next video.",
  "Take care!",
  "Bye for now.",
  "Talk to you later.",
  "Have a great day!",
  "See you soon.",
  "Stay safe!",
  "😳",
  "😣",
  "😥",
  "😢",
  "😭",
  "😨",
  "Take care of yourself.",
  "Keep in touch.",
  "Looking forward to hearing from you.",
  "Let's keep the conversation going.",
  "What are your thoughts on this?",
  "Do you agree or disagree?",
  "What's your experience with this?",
  "What would you like to see next?",
  "What other topics are you interested in?",
  "What are your goals for this year?",
  "What are your hobbies?",
  "What's your favorite food?",
  "What's your favorite movie?",
  "What's your favorite book?",
  "What's your favorite color?",
  "What's your favorite animal?",
  "This is so fun and exciting!",
  "😰",
  "😱",
  "😵",
  "🤪",
  "😶",
  "😐",
  "😑",
  "I'm so glad I chose to watch this!",
  "This is so inspiring and uplifting!",
  "This is so helpful and practical!",
  "This is so well-explained and clear!",
  "I'm so excited to implement what I've learned!",
  "This is so informative and engaging!",
  "This is so fun and lively!",
  "I'm so glad I found this channel!",
  "This is so informative and educational!",
  "I'm so impressed with your skills and talent!",
  "This is so insightful and valuable!",
  "I'm so grateful for your time and effort!",
  "This is so entertaining and captivating!",
  "I'm so excited to see what's next!",
  "This is so well-done and professional!",
  "This is so inspiring and empowering!",
  "I'm so grateful for your support and guidance!",
  "😯",
  "😦",
  "😧",
  "😮",
  "😲",
  "🤔",
  "🤨",
  "💃",
  "This is so fun and engaging!",
  "I'm so glad I decided to watch this!",
  "This is so informative and helpful!",
  "This is so relatable and authentic!",
  "This is so fun and exciting!",
  "I'm so glad I chose to watch this!",
  "This is so inspiring and uplifting!",
  "I'm so impressed with your attention to detail!",
  "This is so helpful and practical!",
  "I'm so grateful for your generosity and kindness!",
  "This is so well-explained and clear!",
  "I'm so excited to implement what I've learned!",
  "This is so fun and lively!",
  "I'm so glad I found this channel!",
  "Hey, what's up?",
  "Hi there!",
  "Hello!",
  "Good to see you here.",
  "How's it going?",
  "What's new with you?",
  "Long time no see!",
  "Nice to meet you.",
  "Thanks for joining the chat.",
  "Hope you're having a good day.",
  "What brings you here today?",
  "How did you find this channel?",
  "What do you think of this video?",
  "Have you tried this before?",
  "What's your favorite part so far?",
  "Do you have any questions?",
  "I'm here to help if you need anything.",
  "Let me know if you have any feedback.",
  "Glad to see you're enjoying the video.",
  "Thanks for watching!",
  "Don't forget to like and subscribe.",
  "See you in the next video.",
  "Take care!",
  "Bye for now.",
  "Talk to you later.",
  "Have a great day!",
  "See you soon.",
  "Stay safe!",
  "Take care of yourself.",
  "Keep in touch.",
  "Looking forward to hearing from you.",
  "Let's keep the conversation going.",
  "What are your thoughts on this?",
  "Do you agree or disagree?",
  "What's your experience with this?",
  "What would you like to see next?",
  "What other topics are you interested in?",
  "What are your goals for this year?",
  "This is so fun and exciting!",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomMessage() {
  return messagesList[Math.floor(Math.random() * messagesList.length)];
}
